version: '3.7'

services:

  db:
    image: postgres
    container_name: prod
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: prod
      POSTGRES_USER: prod
      POSTGRES_PASSWORD: prod