version: '3.7'

services:

  db:
    image: postgres
    container_name: test
    ports:
      - 5433:5433
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test