-- CreateEnum
CREATE TYPE "ERoles" AS ENUM ('ADMIN', 'CREATOR');

-- CreateEnum
CREATE TYPE "EPermissions" AS ENUM ('CREATE_ACCOUNT', 'GET_ACCOUNT', 'GET_ALL_ACCOUNTS', 'UPDATE_ACCOUNT', 'DELETE_ACCOUNT');
